In [5]:
import pandas as pd
import os
import glob
import sys
import gget
import mygene

In [6]:
fpath = "/nfs/turbo/umms-indikar/shared/projects/cell_cycle/data/liu_2017/GSE94479_GROCountNorm.txt.gz"

df = pd.read_csv(fpath, sep=" ")
gene_map = dict(zip(df['refseq'].values, df['id'].values))
df.head()

,G0_G11,G0_G12,S1,S2,G2_M1,G2_M2,refseq,id
NM_032291_chr1_67210769_f,11,2,3,1,3,1,NM_032291,SGIP1
NM_013943_chr1_25170816_f,2883,3103,3717,3697,3938,4095,NM_013943,CLIC4
NM_001145277_chr1_16786585_f,460,460,416,388,410,430,NM_001145277,NECAP2
NM_052998_chr1_33586133_f,100,105,119,110,201,189,NM_052998,ADC
NM_001080397_chr1_8404228_f,84,78,187,175,76,82,NM_001080397,SLC45A1

In [25]:
dpath = "/nfs/turbo/umms-indikar/shared/projects/cell_cycle/data/liu_2017/"

file_list = glob.glob(f"{dpath}*Deseq*")

padj = 0.05
log2FoldChange = 0.0

result = []

for fpath in file_list:
    basename = os.path.basename(fpath).replace(".txt.gz", "")
    phase = basename.split("_")[-1]

    df = pd.read_csv(fpath, sep='\t')
    df = df.drop(columns=['Unnamed: 0', 'pvalue', 'stat'])
    df['sig_a05'] = (df['padj'] < padj)
    df['upregulated'] = (df['log2FoldChange'] > 0)
    df['gene_name'] = df['id'].map(gene_map)
    df['phase'] = phase
    result.append(df)

        
result = pd.concat(result)
print(f"{result.shape=}")
outpath = "../../resources/liu_2017_genes.csv"
result.to_csv(outpath, index=False)
result.head()

result.shape=(63252, 9)

,baseMean,log2FoldChange,lfcSE,padj,id,sig_a05,upregulated,gene_name,phase
0,2.00,2.118778e-07,0.252254,NaN,NM_032291,False,True,SGIP1,G2MvsS
1,3861.75,1.148291e-01,0.060577,1.224995e-01,NM_013943,False,True,CLIC4,G2MvsS
2,411.00,6.118874e-02,0.123772,7.403877e-01,NM_001145277,False,True,NECAP2,G2MvsS
3,154.75,7.121628e-01,0.183383,4.895194e-04,NM_052998,True,True,ADC,G2MvsS
4,130.00,-1.091200e+00,0.199255,3.672817e-07,NM_001080397,True,False,SLC45A1,G2MvsS

In [22]:
result[result['gene_name'] == 'SIM1']

,baseMean,log2FoldChange,lfcSE,padj,id,sig_a05,upregulated,gene_name,phase
14309,148.75000,2.936892,0.233366,1.619289e-34,NM_005068,True,True,SIM1,G2MvsS
14309,26.37649,0.106182,0.387704,8.326027e-01,NM_005068,False,True,SIM1,SvsG0G1
14309,155.25932,3.213273,0.249179,1.316069e-36,NM_005068,True,True,SIM1,G2MvsG0G1

In [23]:
df['log2FoldChange'].min()

-5.44809052253235

In [ ]:
break